# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "gusztavvargadr/windows-10"
	config.vm.box_version = "2511.0.0"

	config.vm.provider :virtualbox do |vb|
		vb.name = "Vagr.test.Interfaces"
		vb.memory = 6144
		vb.cpus = 3
		vb.gui = false
	end	
end
