# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "gusztavvargadr/windows-10"
	config.vm.box_version = "2511.0.0"
	config.vm.define = "Vagr.Maquina.Interfaces"
	config.vm.hostname = "InterfaceDeveloper"
	config.vm.provider :virtualbox do |vb|
		vb.name = "Vagr.Maquina.Interfaces"
		vb.memory = 16384
		vb.cpus = 4
		vb.gui = true
	end
	$script = <<-script
		winget install
	SCRIPT
	config.vm.provision "shell", inline: $script
end
